name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore TaskManagementSystem/TaskManagementSystem.sln

      - name: Build
        run: dotnet build TaskManagementSystem/TaskManagementSystem.sln --no-restore

      - name: Create TestResults folder
        run: mkdir -p TaskManagementSystem.Tests/TestResults

      - name: Test with coverage
        run: dotnet test TaskManagementSystem.Tests/TaskManagementSystem.Tests.csproj --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=TaskManagementSystem.Tests/TestResults/coverage.xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: TaskManagementSystem.Tests/TestResults/coverage.xml
