name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore TaskManagementSystem/TaskManagementSystem.sln

      - name: Build solution
        run: dotnet build TaskManagementSystem/TaskManagementSystem.sln --no-restore

      - name: Run tests with coverage (Cobertura format)
        run: |
          dotnet test TaskManagementSystem.Tests/TaskManagementSystem.Tests.csproj \
            --collect:"XPlat Code Coverage" \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=cobertura

      - name: List TestResults folder contents
        run: |
          find . -type d -name "TestResults" -exec ls -l {} \; || echo "No TestResults folder found"

      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Generate HTML + XML summary coverage report
        run: |
          reportgenerator \
            -reports:**/TestResults/*/coverage.cobertura.xml \
            -targetdir:coverage-report \
            -reporttypes:"Html;XmlSummary"

      - name: Show coverage summary XML
        run: cat coverage-report/Summary.xml

      - name: Enforce minimum coverage threshold
        run: |
          if ! command -v xmllint &> /dev/null; then sudo apt-get install -y libxml2-utils; fi
          COVERAGE_RATE=$(xmllint --xpath "string(//CoverageReport/Summary/Linecoverage)" coverage-report/Summary.xml)
          if [ -z "$COVERAGE_RATE" ]; then
            echo "ERROR: Coverage rate not found in Summary.xml"
            exit 1
          fi
          echo "Raw coverage rate: $COVERAGE_RATE"
          COVERAGE_PERCENT=$(printf "%.0f" "$COVERAGE_RATE")
          echo "Total line coverage: $COVERAGE_PERCENT%"

          THRESHOLD=80
          if [ "$COVERAGE_PERCENT" -ge "$THRESHOLD" ]; then
            echo "Coverage meets threshold ($THRESHOLD%)"
          else
            echo "Coverage below threshold ($THRESHOLD%). Failing build."
            exit 1
          fi

      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v4
        with:
          name: html-coverage-report
          path: coverage-report/
