name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore TaskManagementSystem/TaskManagementSystem.sln

      - name: Build solution
        run: dotnet build TaskManagementSystem/TaskManagementSystem.sln --no-restore

      - name: Run tests with coverage
        run: dotnet test TaskManagementSystem.Tests/TaskManagementSystem.Tests.csproj --collect:"XPlat Code Coverage"

      - name: Upload coverage files
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: '**/TestResults/**/*.coverage'
